language: python

sudo: false

python:
  - "3.6"
  - "3.8"

install:
  # Fetch and install conda
  # -----------------------
  - export CONDA_BASE="http://repo.continuum.io/miniconda/Miniconda"
  - wget ${CONDA_BASE}3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p ${HOME}/miniconda
  - export PATH="${HOME}/miniconda/bin:${PATH}"

  # Create the testing environment
  # ------------------------------
  - conda config --set always_yes true
  - conda config --set changeps1 no
  - conda config --set show_channel_urls true
  - conda config --add channels conda-forge
  - conda update --quiet conda
  - ENV_NAME="test-environment"
  - conda create --quiet -n ${ENV_NAME} python=${TRAVIS_PYTHON_VERSION} --file conda-requirements.txt
  - source activate ${ENV_NAME}
  - git clone https://github.com/minaskar/zeus/ && pushd zeus && python setup.py install && popd; rm -rf zeus

  # Customise the testing environment
  # ---------------------------------
  - pip install coveralls

  # Summerise environment
  # ---------------------
  - conda list
  - conda info -a

  # Install and test autoemcee
  - python setup.py install

script:
  - coverage run setup.py test

after_success: coveralls
