language: python

sudo: false

python:
  - "3.5"
  - "3.8"

install:
  # Install and test autoemcee
  - python setup.py install
  - pip install -e .

script:
  - coverage run setup.py test

after_success: coveralls
